name: Build Extension ZIP via Artifact

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.12.0'  # Change this to your Node.js version if needed

      - name: Install dependencies
        run: npm install
      
      - name: Build Extension
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: './dist'
